SELECT
    O.ID, O.GENOTYPE, P.GENOTYPE AS PARENT_GENOTYPE
FROM
    ECOLI_DATA O
    INNER JOIN
        ECOLI_DATA P
    ON
        P.ID = O.PARENT_ID
WHERE
    (O.GENOTYPE & P.GENOTYPE) = P.GENOTYPE
ORDER BY
    O.ID ASC;