SELECT
    r.REST_ID,
    i.REST_NAME,
    i.FOOD_TYPE,
    i.FAVORITES,
    i.ADDRESS,
    ROUND(AVG(r.REVIEW_SCORE), 2) AS SCORE
FROM
    REST_REVIEW r
        LEFT JOIN
            REST_INFO i
        ON
            r.REST_ID = i.REST_ID
WHERE
    i.ADDRESS LIKE '서울%'
GROUP BY
    REST_ID
ORDER BY
    SCORE DESC,
    FAVORITES DESC;